[env]
TERM = "xterm-256color"

[colors.cursor]
cursor = "#00ffff"
text = "#000000"

[colors.primary]
background = "#1b1e2b"
foreground = "#AEB7B6"
    
[colors.normal]
black =   "#1d1f21"
red =     "#CF3746"
green =   "#7CBD27"
yellow =  "#ECBD10"
blue =    "#277AB6"
magenta = "#AD4ED2"
cyan =    "#32B5C7"
white =   "#d8e2e1"

[colors.bright]
black =   "#292A2B"
red =     "#d95473"
green =   "#b6da74"
yellow =  "#e7ca62"
blue =    "#64a8d8"
magenta = "#bc82d3"
cyan =    "#65cedc"
white =   "#ebf6f5"

[window.padding]
x = 6
y = 6

[font]
size = 14.0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bolt"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
