backend = "xrender";
glx-no-stencil = true;
glx-copy-from-front = false;

shadow = false;

shadow-exclude = [
    "name = 'Notification'",
    "name *= 'VLC'",
    "name *= 'picom'",
    "class_g = 'Firefox' && argb",
    "class_g ?= 'Notify-osd'",
    "_GTK_FRAME_EXTENTS@:c",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
    "n:e:Menu"
];
shadow-ignore-shaped = false;

active-opacity = 1;
inactive-opacity = 1;

wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.9; focus = true;};
  dock = { shadow = false; };
  dnd = { shadow = false; };
  menu = { shadow = false; };
  popup_menu = { shadow = false; };
  dropdown_menu = { shadow = false; }
};
